export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  USER = 'USER',
  SCHOOL_ADMIN = 'SCHOOL_ADMIN',
  SCHOOL_STAFF = 'SCHOOL_STAFF',
  SCHOOL_STUDENT = 'SCHOOL_STUDENT',
  SCHOOL_PARENT = 'SCHOOL_PARENT',
  SCHOOL_GUEST = 'SCHOOL_GUEST'
}
